### PR TITLE
Added arrow keys to change slides

### PR DESCRIPTION
**Pull request by LucasReimold**
Arrowkeys left and right changes slides to next / previous in presentation mode.

### CODE REVIEW

**Comment by pezubi** [comment]
Wow, what a great idea!! :partying_face:

**Comment by johndoe31415** [comment]
Hey @LucasReimold, unfortunately there's a huge merge conflict that I'd like to ask you to reconcile.

Also, just for future reference, I'm guessing that the excellence of the submitted code stems from the fact you were acting under the Ballmer Peak?

**Comment by LucasReimold** [comment]
Hey @johndoe31415, the merge conflict should be resolved now.
You were almost right before - I drank one or two "Club Mate" too much.

**Comment by johndoe31415** [comment]
I've merged this absolute marvel of engineering in cb0ebfe.

Remember to drink "Mate" responsibly, Mr. Reimold 😉

**Pull request closed without merging**
